networks:
  airline: {}

volumes:
  mysql-data: {}
  airline-target: {}

services:
  airline-app:
    container_name: airline-app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      airline-db:
        condition: service_healthy
      airline-search:
        condition: service_started
    volumes:
      - ".:/home/airline/airline"
      - "./.docker/data/init.sh:/home/airline/init-data.sh"
      - "./.docker/data/start.sh:/home/airline/start-data.sh"
      - "./.docker/web/start.sh:/home/airline/start-web.sh"
      - "./.docker/web/clean.sh:/home/airline/clean-web.sh"
      - "./.docker/start-all.sh:/home/airline/start-all.sh"
      - "./.docker/check-init-status.sh:/home/airline/check-init-status.sh"
      - "./.docker/wait-for-mysql.sh:/home/airline/wait-for-mysql.sh"
    environment:
      DB_HOST: airline-db
      ES_HOST: airline-search
    entrypoint: ["tail", "-f", "/dev/null"]
#    ports:
#      - "9000:9000"
    healthcheck:
      test: curl --fail http://localhost:9000/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - airline

  airline-db:
    image: bitnami/mysql:8.0
    container_name: airline-db
    environment:
      MYSQL_DATABASE: airline
      MYSQL_USER: mfc01
      MYSQL_PASSWORD: ghEtmwBdnXYBQH4
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATE: utf8mb4_unicode_ci
      ALLOW_EMPTY_PASSWORD: yes
#    ports:
#      - "3306:3306"
    volumes:
      - "mysql-data:/bitnami/mysql/data"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mfc01", "-pghEtmwBdnXYBQH4"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - airline

  airline-search:
    image: elasticsearch:7.17.21
    container_name: airline-search
    environment:
      discovery.type: single-node
    networks:
      - airline
